app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    def save_user(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'User {self.username}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class BlogForm(FlaskForm):

    title = StringField('Blog category',validators=[Required()])
    description = TextAreaField('Write Blog', validators=[Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):

    title = StringField('Blog title',validators=[Required()])
    comment = TextAreaField('Blog feedback', validators=[Required()])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Add Bio')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app   configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

     # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

     # configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import User
from .forms import BlogForm,CommentForm,UpdateProfile
from flask_login import login_required
from .. import db,photos


#comment
@main.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''
    title = 'Home'
    return render_template('index.html',title = title)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block styles%}
{{ super() }}

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/css/mdb.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Courgette&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lora&display=swap" rel="stylesheet">
  <link href="/static/css/styles.css" rel="stylesheet">
 

{% endblock %}

 <!-- Navbar block  --> 
 {% block navbar %}

 {% include 'navbar.html' %}

 {% endblock %}

 {% block scripts %}
 {{ super() }}

 <!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/js/mdb.min.js"></script>

{% endblock %}


  

       
     
  

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}

    <h1>WHOOOPS we can't find that page</h1>
    
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}

{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Book</title>
</head>
<body>
    
</body>

</html>
{% endblock%}

app/templates/navbar.html
<!--Navbar -->
<nav class="mb-1 navbar navbar-expand-lg navbar-dark success-color">
        <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a style="font-size: 24px" class="nav-link" href="/">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item dropdown">
                    <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                      <a style="font-size: 15px" class="dropdown-item" href="/football">Football</a>
                      <a style="font-size: 15px" class="dropdown-item" href="/cycling">Cycling</a>
                      <a style="font-size: 15px" class="dropdown-item" href="/rugby">Rugby</a>
                      <a style="font-size: 15px" class="dropdown-item" href="/basketball">Basket ball</a>
                    </div>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li><a style="font-size: 17px" href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
            <li style="color:white;padding:15px; font-size: 17px;">{{current_user.username}}</li>
            <li><a style="font-size: 24px; color: white;" href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a style="font-size: 24px; color: white;" href="{{url_for('auth.login')}}">Sign in</a></li>
            {%endif%}
          </ul>
        </div>
</nav>
<!--/.Navbar -->

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">

        <div class="col-md-4">
            {{ wtf.quick_form(comment_form) }}
        </div>

    </div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}

<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="">
    <h3 style="font-size: 20px"> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p style="font-size: 20px"> {{user.bio}}</p>
    {%else%}
      <p style="font-size: 20px"> {{user.username| capitalize}} has no bio </p>
    {% endif %}

    {% if user == current_user %}
    <a style="font-size: 13px" class="btn btn-success btn-rounded mb-4" href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}

  <!--Display profile photo-->
  <div class="">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p style="font-size: 20px">No profile picture</p>
    {% endif %}

    {% if user == current_user %}
    <br>
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">
      <br>

      <input type="file" width="30%" name="photo" class="form-control form-control-lg" required>
      <br>
      <input style="font-size: 13px" type="submit" class="btn btn-success btn-rounded mb-4">
    </form>
    {% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}